### PR TITLE
Fix bugs and update UG

### LINKED ISSUE #194: [UG] Fix syntax bolding for client, add symbols and other enhancements
Some of the texts are not consistent in terms of their syntax and highlights (expected output not bolded, "You should see the following output if the client is created successfully.", etc)

- [x] [UG] -cn client_name
The client’s name. Alphanumerical characters only.
- [x] Fix Message_not_edited constant in UpdateClientCommand.java
- [x] Fix Message_success constant in UpdateClientCommand.java
- [x] [UG] Add note on what is a valid year of birth

### PR DESCRIPTION
**Pull request by Douglch**
Closes #194  #200 
Note: This PR does not contain the latest UG version

### CODE REVIEW

File: src/main/java/mycelium/mycelium/model/person/Name.java [hunk 1]
```diff
@@ -3,21 +3,21 @@
...
+
 /**
  * Represents a Person's name in the address book.
  * Guarantees: immutable; is valid as declared in {@link #isValidName(String)}
  */
 public class Name {
 
-    public static final String MESSAGE_CONSTRAINTS =
-        "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+    public static final String MESSAGE_CONSTRAINTS = NonEmptyString.MESSAGE_CONSTRAINTS;
```
Comment (immanuelhume) [inline src/main/java/mycelium/mycelium/model/person/Name.java:15]:
```suggestion
    public static final String MESSAGE_CONSTRAINTS = "Name cannot be empty or consist only of whitespace";
```

File: docs/UserGuide.md [hunk 2]
```diff
@@ -175,14 +175,14 @@ Creates a new client contact.
...
-    - The client’s name.
+    - The client’s name. Alphanumerical characters only. Case sensitive.
 - `-e email`
     - The client’s email. Must be unique in Mycelium. Case sensitive.
 
 **Optional Arguments**
 
 - `-y year_of_birth`
-    - The client’s year of birth.
+    - The client’s year of birth. A valid year of birth is between 1900 and 2023, inclusive.
```
Comment (immanuelhume) [inline docs/UserGuide.md:185]: based on the YearOfBirth class it should be [0000, 9999]
```suggestion
    - The client’s year of birth. Any combination of four digits is acceptable.
```

File: docs/UserGuide.md [hunk 3]
```diff
@@ -175,14 +175,14 @@ Creates a new client contact.
 **Compulsory Arguments**
 
 - `-cn client_name`
-    - The client’s name.
+    - The client’s name. Alphanumerical characters only. Case sensitive.
```
Comment (immanuelhume) [inline docs/UserGuide.md:178]:
```suggestion
    - The client’s name.
```

**Review by immanuelhume — APPROVED** [review]
:shipit:
