### PR TITLE
Add small tests, fix overlaps

### LINKED ISSUE #80: Additional tests for Client Model
Tests for:
1. [x] AddressBook - hashCode() and equals()
2. [x] ModelManager - hashCode()
3. [x] serialization test

### PR DESCRIPTION
**Pull request by Douglch**
Closes #80.

Note to self: Only just saw that JY implemented the tests for JsonSerializableAddressBookTest in the PR, so I've reset my part in JsonSerializableAddressBookTest, TypicalPersons 😢 (will check PR first before coding anythn).

### CODE REVIEW

File: src/test/java/mycelium/mycelium/storage/JsonAdaptedClientTest.java [hunk 1]
```diff
@@ -24,6 +23,14 @@ public class JsonAdaptedClientTest {
     private static final String VALID_SOURCE = WEST.getSource().get();
     private static final String VALID_MOBILE_NUMBER = WEST.getMobileNumber().get().value;
 
+    //    @Test
```
Comment (immanuelhume) [inline src/test/java/mycelium/mycelium/storage/JsonAdaptedClientTest.java:26]: is this part commented out coz not working for now?

File: src/test/java/mycelium/mycelium/model/ModelManagerTest.java [hunk 2]
```diff
@@ -287,8 +288,12 @@ public void getFilteredProjectList_modifyList_throwsUnsupportedOperationExceptio
 
     @Test
     public void equals() {
```
Comment (immanuelhume) [inline src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: I just realized AB3 wrote this test in a pretty confusing way lmao. It's doing so much random shit in one fn. I think I'll try to refactor a bit in the next iteration, but this will do for now :+1:

**Review by immanuelhume — APPROVED** [review]

File: src/test/java/mycelium/mycelium/storage/JsonAdaptedClientTest.java (hunk 1 above)
Comment (Douglch) [reply src/test/java/mycelium/mycelium/storage/JsonAdaptedClientTest.java:26]: yup, it'll work after merging

File: src/test/java/mycelium/mycelium/model/ModelManagerTest.java (hunk 2 above)
Comment (Douglch) [reply src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: Yeah, I'm thinking of adding a generic for NameContainsKeywordsPredicate class, so it'll become like NameContainsKeywordsPredicate<T>, where T can represent person, client, project. This is cos right now NameContainsKeywordsPredicate class implements Predicate<Person>, and we could change implementation to Predicate<T>. However, if we do change it to <T>, we probably need to refactor like 40 methods to include the generic. What's yo opinion on this? @immanuelhume

Comment (Douglch) [reply src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: This is so that we can test `updateFilteredClientList()` and `updateFilteredProjectList()` from `ModelManger`. Another way would be to just create another 2 classes to implement Predicate, but it would be less clean ig.

Comment (immanuelhume) [reply src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: this is a good idea, but re this predicate thing, seems like it's existence is coz AB3 has a `find` command to find person from their name

we're gna adapt this to do sth different in the next iteration, so it's prolly best to just leave it as is for now to prevent double work. i suspect we'll be able to delete the whole *ContainsKeywordsPredicate thing

maybe can just add  TODO or NOTE to come back and refactor it later, and merge wat we have currently

Comment (immanuelhume) [reply src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: re the testing of `updateFilteredClientList` and `updateFilteredProjectList`, we can have independent tests for them i.e. not inside this big `equals` test, maybe a separate `updateFilteredClientList_allTrueFilter_doesNothing`, `updateFilteredClientList_allFalseFilter_becomesEmpty` etc etc

Comment (Douglch) [reply src/test/java/mycelium/mycelium/model/ModelManagerTest.java:290]: roger that
